from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import os
import datetime
from rag.faiss_store import store_event

def generate_certificate(customer_id, forget_size, model_type, metrics, filename="unlearning_certificate.pdf"):
    """
    Generates a PDF certificate for the unlearning action.
    """
    print("--- Generating Unlearning Certificate ---")
    
    save_path = f"dashboard/{filename}"
    c = canvas.Canvas(save_path, pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width / 2, height - 100, "Certificate of Erasure")
    
    # Subtitle
    c.setFont("Helvetica", 12)
    c.drawCentredString(width / 2, height - 130, "AI Governance & Compliance Logic")
    
    # Line
    c.setLineWidth(1)
    c.line(100, height - 150, width - 100, height - 150)
    
    # Details
    y = height - 200
    c.setFont("Helvetica-Bold", 14)
    c.drawString(100, y, "Transaction Details:")
    
    c.setFont("Helvetica", 12)
    y -= 30
    c.drawString(100, y, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    y -= 25
    c.drawString(100, y, f"Customer ID: {customer_id if customer_id else 'Batch Unlearning'}")
    y -= 25
    c.drawString(100, y, f"Records Removed: {forget_size}")
    y -= 25
    c.drawString(100, y, f"Target Model: {model_type}")
    
    # Metrics
    y -= 50
    c.setFont("Helvetica-Bold", 14)
    c.drawString(100, y, "Verification Metrics:")
    
    c.setFont("Helvetica", 12)
    y -= 30
    c.drawString(100, y, f"Final Accuracy: {metrics.get('accuracy', 'N/A')}")
    y -= 25
    c.drawString(100, y, f"Privacy Risk (MIA): {metrics.get('mia_risk', 'N/A')}")
    y -= 25
    c.drawString(100, y, f"Reversibility Error: {metrics.get('reversibility_error', 'N/A')}")
    
    # Status
    y -= 50
    c.setFont("Helvetica-Bold", 16)
    if metrics.get('compliance', False):
        c.setFillColor(colors.green)
        c.drawString(100, y, "STATUS: COMPLIANT")
    else:
        c.setFillColor(colors.red)
        c.drawString(100, y, "STATUS: PENDING / FAILED")
        
    c.setFillColor(colors.black)
    
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(width / 2, 50, "This document certifies that the specified data has been unlearned from the AI system.")
    c.drawCentredString(width / 2, 35, "Generated by Agentic Orchestrator.")
    
    c.save()
    
    log_msg = f"Certificate generated at {save_path}"
    store_event(log_msg)
    print(log_msg)
    
    return save_path

import json
import numpy as np

class NumpyEncoder(json.JSONEncoder):
    """ Special json encoder for numpy types """
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        elif isinstance(obj, np.bool_):
            return bool(obj)
        return super(NumpyEncoder, self).default(obj)

def save_metrics_json(metrics, filepath="dashboard/latest_metrics.json"):
    try:
        with open(filepath, "w") as f:
            json.dump(metrics, f, cls=NumpyEncoder, indent=4)
        print(f"Metrics saved to {filepath}")
    except Exception as e:
        print(f"Error saving metrics JSON: {e}")
